// Generated by CoffeeScript 1.7.1

/*
  Module dependencies.
 */

(function() {
  var config, express, http, less, path, server;

  express = require('express');

  http = require('http');

  path = require('path');

  less = require('less-middleware');

  config = require('./config');

  server = express();


  /*
    All environments
   */

  server.set('port', process.env.PORT || config.port);

  server.set('views', __dirname + "/views");

  server.set('view engine', 'jade');

  server.use(express.favicon());

  server.use(express.logger('dev'));

  server.use(express.bodyParser());

  server.use(express.methodOverride());

  server.use(express.json());

  server.use(express.urlencoded());

  server.use(server.router);

  server.use(less({
    src: path.join(__dirname, 'public')
  }));

  server.use(express["static"](path.join(__dirname, 'public')));

  if ('development' === server.get('env')) {
    server.use(express.errorHandler());
  }


  /*
  	Define routes
   */

  server.get("/", function(req, res) {
    return res.render("index");
  });

  server.get("/partials/:name", function(req, res) {
    var name;
    name = req.params.name;
    return res.render("partials/" + name);
  });


  /*
  	Startup and log.
   */

  http.createServer(server).listen(server.get("port"), function() {
    return console.log("Express server listening on port " + server.get("port"));
  });

}).call(this);
